"""migration

Revision ID: 9c570fc6e4fc
Revises: 
Create Date: 2021-12-12 16:52:55.765476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c570fc6e4fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorten_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('short_web', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shorten_urls')
    # ### end Alembic commands ###
